### ISSUE TITLE
怎么运行？

### ISSUE THREAD

**Issue by LDX596999414** [Greenzie/boustrophedon_planner#1]
我想把它加入move_base中，请问怎么使用，这只有一个server嘛？

**Comment by Spwizzard** [comment]
Right now it doesn't directly integrate with move_base, you need to set up an intermediary node to turn the striping plan into move_base goals. I'm not sure how you would use this as a move_base global planner since it would need a lot more input data than the `move_base_msgs/MoveBaseActionGoal` can provide.

**Comment by 1234564lll** [comment]
> Right now it doesn't directly integrate with move_base, you need to set up an intermediary node to turn the striping plan into move_base goals. I'm not sure how you would use this as a move_base global planner since it would need a lot more input data than the `move_base_msgs/MoveBaseActionGoal` can provide.

Do you know how to integrate now

**Comment by weicyingqiaopian** [comment]
Do you know how to integrate into move_base?

**Comment by orensbruli** [comment]
Closing this issue.
Archiving the repo.
