### ISSUE TITLE
Support for inner polygon areas to not cover?

### ISSUE THREAD

**Issue by SteveMacenski** [Greenzie/boustrophedon_planner#13]
Hi,

If we had a kitchen with an island, could we create a polygon for that island internal to the outline polygon to stay out of with this implementation?

We're looking at coverage planners for ROS2 / Nav2 integration and this one has come to mind

**Comment by seebq** [comment]
Hey @SteveMacenski we actually open sourced this one and have since wrote another (the great rewrite), since this was GPLv3, and we're more of a BSD-clause-3 type shop, like most of ROS.

We are debating internally right now on how we can open source our new one and find the bandwidth to actually do it and maintain it (as this library lacks a maintainer right now).  I wouldn't pull this one in for ROS2 / Nav2 yet.

As to creating a polygon for that internal island, that's not really something you can do with this one. 

We don't have support for it on the new one either but we suspect it will be much less painful to do on our new one than to try to update this one.

We are interested in helping out on this!  Where can we go to learn more, do you have a discourse or other area where you are discussing this?

**Comment by SteveMacenski** [comment]
> since this was GPLv3

Admittedly, that's the thing that turned me off the most about this, so glad to hear! Most of ROS2 is Apache 2.0 (functionally the same for everyone, gives you some patent protections). 

> How we can open source our new one and find the bandwidth to actually do it and maintain it

Given what I see here, its maintained well enough, only 6 tickets, no outstanding PRs, etc. If the version you're thinking about you actually use internally, then I think maintenance is intrinsically easier. If someone submits an actual bug or a new feature, there's business value in responding / merging the fixes because it impacts and improves your systems as well. I agree its hard to justify time to maintain something you don't use, so just make sure you open what you use!

> We don't have support for it on the new one either but we suspect it will be much less painful to do on our new one than to try to update this one.

Got it - is this something you have business value in implementing (I'd think with tree and such there would be)? I haven't looked into the technology to a deep level, but I agree its definitely possible to add it. The eth-asl one does this, but LGPLv3.

> We are interested in helping out on this! Where can we go to learn more, do you have a discourse or other area where you are discussing this?

We're discussing this on the Nav2 slack group in the #planning channel. https://discourse.ros.org/t/nav2-new-controller-plugin-regulated-pure-pursuit/18928 you can find a link to join in this post. I'm also chatting about this privately with Nobleo, who has their own coverage planner - but the reason yours is compelling is because you use it and rely on it so there's built in users (and maybe help push over to use Nav2 if we integrate it ;-) )

**Comment by weicyingqiaopian** [comment]
Do you know how to integrate into move_base?
